name: Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Install ArgoCD CLI
      run: |
        wget https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -O /usr/local/bin/argocd
        chmod +x /usr/local/bin/argocd

    - name: Log in to ArgoCD
      run: argocd login murierromain.com:8080 --username admin --password miwaber7896MIOP/ --insecure

    - name: Check if the application exists
      id: check_application
      run: |
        set +e
        argocd app get TestDotNet
        exists=$?
        set -e
        echo "::set-output name=exists::$exists"

    - name: Create application if not exists
      if: steps.check_application.outputs.exists != 0
      run: |
        argocd app create TestDotNet \
          --repo https://github.com/RMurier/testArgoCd \
          --path path/to/your/application \
          --dest-namespace default \
          --dest-server https://kubernetes.default.svc \
          --sync-policy automated \
          --username RMurier \
          --password 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

    - name: Sync application with ArgoCD
      run: argocd app sync TestDotNet