name: Deploy to ArgoCD

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Install ArgoCD CLI
      run: |
        wget https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -O /usr/local/bin/argocd
        chmod +x /usr/local/bin/argocd

    - name: Log in to ArgoCD
      run: argocd login murierromain.com:8080 --username admin --password miwaber7896MIOP/ --insecure

    - name: Sync application with ArgoCD
      run: argocd app sync TestDotNet
